### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by KeraMiT** [RitaSister/WorldGuardRegionProtect#12]
### Server Implementation

Purpur

### Server Version

1.16.5

### Describe the bug

Вся информация ниже, ошибка при запуске.

### To Reproduce

1. Список плагинов ниже.

### Expected behaviour

Что тут писать?

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/89001036/151929771-d359ba4c-2f5d-499b-a42f-e604ff058aab.png)
![image](https://user-images.githubusercontent.com/89001036/151929772-638b05e2-9e45-456f-b201-e775f21238a4.png)

### Error log (if applicable)

[09:29:14 WARN]: [DonateCase] Loaded class me.leoko.advancedban.shaded.org.hsqldb.jdbc.JDBCDriver from AdvancedBan v2.3.0 which is not a depend, softdepend or loadbefore of this plugin. [09:29:14 WARN]: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure [09:29:14 WARN]: [09:29:14 WARN]: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server. [09:29:14 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) [09:29:14 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) [09:29:14 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833) [09:29:14 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) [09:29:14 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) [09:29:14 WARN]:        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) [09:29:14 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677) [09:29:14 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228) [09:29:14 WARN]:        at net.ritasister.dc.MySQL.<init>(MySQL.java:21) [09:29:14 WARN]:        at net.ritasister.dc.DonateCase$1.run(DonateCase.java:93) [09:29:14 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) [09:29:14 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) [09:29:14 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1083) [09:29:14 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) [09:29:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831) [09:29:14 WARN]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure [09:29:14 WARN]: [09:29:14 WARN]: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server. [09:29:14 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [09:29:14 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) [09:29:14 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [09:29:14 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) [09:29:14 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) [09:29:14 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) [09:29:14 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) [09:29:14 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) [09:29:14 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) [09:29:14 WARN]:        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89) [09:29:14 WARN]:        at com.mysql.cj.NativeSession.connect(NativeSession.java:144) [09:29:14 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953) [09:29:14 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823) [09:29:14 WARN]:        ... 12 more [09:29:14 WARN]: Caused by: java.net.ConnectException: Connection refused: no further information [09:29:14 WARN]:        at java.base/sun.nio.ch.Net.pollConnect(Native Method) [09:29:14 WARN]:        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:669) [09:29:14 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) [09:29:14 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) [09:29:14 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333) [09:29:14 WARN]:        at java.base/java.net.Socket.connect(Socket.java:645) [09:29:14 WARN]:        at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155) [09:29:14 WARN]:        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63) [09:29:14 WARN]:        ... 15 more [09:29:14 INFO]: [DonateCase] Disabling DonateCase v0.1.6 [09:29:14 WARN]: [DonateCase] Task #24 for DonateCase v0.1.6 generated an exception java.lang.NullPointerException: Cannot invoke "java.sql.Statement.executeQuery(String)" because "this.stmt" is null         at net.ritasister.dc.MySQL.hasTable(MySQL.java:70) ~[?:?]         at net.ritasister.dc.DonateCase$1.run(DonateCase.java:94) ~[?:?]         at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]         at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1171]         at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1083) ~[patched_1.16.5.jar:git-Purpur-1171]         at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]         at java.lang.Thread.run(Thread.java:831) [?:?]

### WorldGuardRegionProtect version

7

### Checklist

- [X] I am using the newest build from https://github.com/RitaSister/ServerRegionProtect/releases/ and the issue still persists.

**Comment by RitaSister** [comment]
Вы написали не для того плагина запрос.

**Comment by KeraMiT** [comment]
> Вы написали не для того плагина запрос.

Но можно получить ответ, мне очень нужен DonateCase плагин.
