### ISSUE TITLE
PaperMC [1.17.1]

### ISSUE THREAD

**Issue by kiskaserver** [RitaSister/WorldGuardRegionProtect#6]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Не запускается на ядре PaperMC. 
При попытке запустить
Хотелось бы работоспособную версию и команды.
Например: /wgrp add <region>, /wgrp del <region>, /wgrp list <region>. 

LOG:
00:40:05] [Server thread/INFO]: [WorldGuardRegionProtect] Enabling WorldGuardRegionProtect v0.7.0
[00:40:05] [Server thread/WARN]: [RSLibrary-Logger] ВYou are running is Вjava Вversion: В17
[00:40:05] [Server thread/WARN]: [RSLibrary-Logger] ВYour Вserver Вis running version: Вv1_17_R1
[00:40:05] [Server thread/WARN]: [RSLibrary-Logger] ВPlugin: WorldGuard loaded successful!.
[00:40:05] [Server thread/ERROR]: Cannot load plugins\WorldGuardRegionProtect\config.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 129, column 7:
          console: true
          ^
expected <block end>, but found '<block mapping start>'
 in 'string', line 133, column 9:
            sound: true
            ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[patched_1.17.1.jar:git-Paper-349]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.17.1.jar:git-Paper-349]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.17.1.jar:git-Paper-349]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:188) ~[patched_1.17.1.jar:git-Paper-349]
	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:158) ~[patched_1.17.1.jar:git-Paper-349]
	at net.ritasister.util.config.UtilConfig.<init>(UtilConfig.java:35) ~[WorldGuardRegionProtect-0.7.0.jar:?]
	at net.ritasister.util.UtilConfigManager.loadConfig(UtilConfigManager.java:14) ~[WorldGuardRegionProtect-0.7.0.jar:?]
	at net.ritasister.wgrp.WorldGuardRegionProtect.onEnable(WorldGuardRegionProtect.java:39) ~[WorldGuardRegionProtect-0.7.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-349]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-349]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-349]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-349]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-349]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:730) ~[patched_1.17.1.jar:git-Paper-349]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-349]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[patched_1.17.1.jar:git-Paper-349]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-349]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 129, column 7:
          console: true
          ^
expected <block end>, but found '<block mapping start>'
 in 'string', line 133, column 9:
            sound: true
            ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:617) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:221) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:191) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:146) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[patched_1.17.1.jar:git-Paper-349]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[patched_1.17.1.jar:git-Paper-349]
	... 17 more
[00:40:05] [Server thread/ERROR]: Cannot load configuration from stream
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 129, column 7:
          console: true
          ^
expected <block end>, but found '<block mapping start>'
 in 'string', line 133, column 9:
            sound: true
            ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[patched_1.17.1.jar:git-Paper-349]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.17.1.jar:git-Paper-349]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:217) ~[patched_1.17.1.jar:git-Paper-349]
	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:165) ~[patched_1.17.1.jar:git-Paper-349]
	at net.ritasister.util.config.UtilConfig.<init>(UtilConfig.java:35) ~[WorldGuardRegionProtect-0.7.0.jar:?]
	at net.ritasister.util.UtilConfigManager.loadConfig(UtilConfigManager.java:14) ~[WorldGuardRegionProtect-0.7.0.jar:?]
	at net.ritasister.wgrp.WorldGuardRegionProtect.onEnable(WorldGuardRegionProtect.java:39) ~[WorldGuardRegionProtect-0.7.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-349]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-349]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-349]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-349]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-349]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:730) ~[patched_1.17.1.jar:git-Paper-349]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-349]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[patched_1.17.1.jar:git-Paper-349]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-349]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 129, column 7:
          console: true
          ^
expected <block end>, but found '<block mapping start>'
 in 'string', line 133, column 9:
            sound: true
            ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:617) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:221) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:191) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:146) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[patched_1.17.1.jar:git-Paper-349]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[patched_1.17.1.jar:git-Paper-349]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[patched_1.17.1.jar:git-Paper-349]
	... 16 more
[00:40:05] [Server thread/ERROR]: Error occurred while enabling WorldGuardRegionProtect v0.7.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getList(String, java.util.List)" because the return value of "net.ritasister.util.config.UtilConfig.getPatch()" is null
	at net.ritasister.util.config.UtilConfig.<init>(UtilConfig.java:37) ~[WorldGuardRegionProtect-0.7.0.jar:?]
	at net.ritasister.util.UtilConfigManager.loadConfig(UtilConfigManager.java:14) ~[WorldGuardRegionProtect-0.7.0.jar:?]
	at net.ritasister.wgrp.WorldGuardRegionProtect.onEnable(WorldGuardRegionProtect.java:39) ~[WorldGuardRegionProtect-0.7.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-349]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-349]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-349]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-349]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-349]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:730) ~[patched_1.17.1.jar:git-Paper-349]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-349]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[patched_1.17.1.jar:git-Paper-349]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-349]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:40:05] [Server thread/INFO]: [WorldGuardRegionProtect] Disabling WorldGuardRegionProtect v0.7.0

### To Reproduce

1. Запустил сервер
2. Подождал пока загрузиться
3. Всплыл данный баг и плагин выключился.

### Expected behaviour

Я думаю что в плагине отсуствует либо устарела какая-то библиотека

### WorldGuardRegionProtect version

7.0.6 / 0.7.0

### Checklist

- [x] I am using the newest build from https://github.com/RitaSister/ServerRegionProtect/releases/ and the issue still persists.

**Comment by kiskaserver** [comment]
ID не верный

**Comment by RitaSister** [comment]
Да, ошибка. RitaSister#0664
пропущен нолик был.
